name: Build Irssi

on:
  push:
    branches:
      - ino_dev  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            libssl-dev \
            pkg-config \
            libglib2.0-dev

      - name: Prepare and build
        run: |
          ./autogen.sh
          ./configure
          make

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: irssi-binary
          path: src/irssi

